### ISSUE TITLE
I keep getting this error duriong cmake ?

### ISSUE THREAD

**Issue by arsalan993** [MichalBusta/DeepTextSpotter#13]
During cmake of caffe:

CMake Warning at /usr/share/cmake-3.7/Modules/FindBoost.cmake:761 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindBoost.cmake:865 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.7/Modules/FindBoost.cmake:1470 (_Boost_MISSING_DEPENDENCIES)
  cmake/Dependencies.cmake:8 (find_package)
  CMakeLists.txt:46 (include)

CMake Warning at /usr/share/cmake-3.7/Modules/FindBoost.cmake:761 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindBoost.cmake:865 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.7/Modules/FindBoost.cmake:1470 (_Boost_MISSING_DEPENDENCIES)
  cmake/Dependencies.cmake:8 (find_package)
  CMakeLists.txt:46 (include)

CMake Warning at /usr/share/cmake-3.7/Modules/FindBoost.cmake:761 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindBoost.cmake:865 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.7/Modules/FindBoost.cmake:1470 (_Boost_MISSING_DEPENDENCIES)
  cmake/Dependencies.cmake:8 (find_package)
  CMakeLists.txt:46 (include)

-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Error at /usr/share/cmake-3.7/Modules/FindBoost.cmake:1831 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  cmake/Dependencies.cmake:8 (find_package)
  CMakeLists.txt:46 (include)

-- Found GFlags: /usr/include  
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found Glog: /usr/include  
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found version "3.0.0") 
-- Found PROTOBUF Compiler: /usr/bin/protoc
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- HDF5: Using hdf5 compiler wrapper to determine CXX configuration
-- Found HDF5: /usr/lib/x86_64-linux-gnu/libhdf5_cpp.so;/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "1.10.0.1") found components:  HL 
CMake Error at /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find LMDB (missing: LMDB_INCLUDE_DIR LMDB_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindLMDB.cmake:19 (find_package_handle_standard_args)
  cmake/Dependencies.cmake:52 (find_package)
  CMakeLists.txt:46 (include)

-- Configuring incomplete, errors occurred!
See also "/home/test/Desktop/DeepTextSpotter/caffe/Release/CMakeFiles/CMakeOutput.log".
See also "/home/test/Desktop/DeepTextSpotter/caffe/Release/CMakeFiles/CMakeError.log".

**Comment by arsalan993** [comment]
and when i cmake this project i get this error:

-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable version "2.7.13", minimum required is "2.7") 
CMake Error at CMakeLists.txt:5 (find_package):
  By not providing "FindNumPy.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "NumPy", but
  CMake did not find one.

  Could not find a package configuration file provided by "NumPy" with any of
  the following names:

    NumPyConfig.cmake
    numpy-config.cmake

  Add the installation prefix of "NumPy" to CMAKE_PREFIX_PATH or set
  "NumPy_DIR" to a directory containing one of the above files.  If "NumPy"
  provides a separate development package or SDK, be sure it has been
  installed.


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.7)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/home/test/Desktop/DeepTextSpotter/src/build/CMakeFiles/CMakeOutput.log".

**Comment by arsalan993** [comment]
I am using caffe version 1.0.0-rc4 
unable to import caffe using any of the python version
ubuntu 17.04
cmake version 3.7.2

**Comment by MichalBusta** [comment]
Hi, 
the first error message is telling you, that cmake can not find boost libraries: 
 - you can fix this by:

sudo apt-get install libboost-all-dev

**Comment by arsalan993** [comment]
Now i am getting this error during cmake of caffe

 cmake -D CMAKE_BUILD_TYPE=Release -D BLAS=Open -D BUILD_SHARED_LIBS=Off ..
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   system
--   thread
--   filesystem
--   chrono
--   date_time
--   atomic
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Found PROTOBUF Compiler: /usr/bin/protoc
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- HDF5: Using hdf5 compiler wrapper to determine CXX configuration
-- Found lmdb    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/liblmdb.so)
CMake Error at /usr/local/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find LevelDB (missing: LevelDB_INCLUDE LevelDB_LIBRARY)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindLevelDB.cmake:18 (find_package_handle_standard_args)
  cmake/Dependencies.cmake:63 (find_package)
  CMakeLists.txt:46 (include)


-- Configuring incomplete, errors occurred!
See also "/home/test/Desktop/DeepTextSpotter/caffe/Release/CMakeFiles/CMakeOutput.log".
See also "/home/test/Desktop/DeepTextSpotter/caffe/Release/CMakeFiles/CMakeError.log".

**Comment by MichalBusta** [comment]
this will help: http://caffe.berkeleyvision.org/install_apt.html

**Comment by gengkunling** [comment]
When I tried to cmake the project, I also encountered this error:


-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable version "2.7.13", minimum required is "2.7")
CMake Error at CMakeLists.txt:5 (find_package):
By not providing "FindNumPy.cmake" in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by "NumPy", but
CMake did not find one.

Could not find a package configuration file provided by "NumPy" with any of
the following names:

NumPyConfig.cmake
numpy-config.cmake

Have you found a way to solve this issue? @arsalan993

**Comment by abhi-kumar** [comment]
That is because the CMAKE_MODULE_PATH may not been set correctly. This path needs to have your FindNumPy.cmake which currently resides in your src directory.

A temporary solution could be to add these lines to your CMakeLists file:
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "<Path to your src directory>")
set (CMAKE_CXX_STANDARD 11)

I has to add the second line to ensure proper compilation without the error: 
/home/abhi/Desktop/Work/doc_scanner/DeepTextSpotter/src/trie.hpp:21:20: error: ISO C++ forbids declaration of ‘it’ with no type [-fpermissive]
   for( const auto &it : children )

Hope this helps you.

**Comment by DreadPiratePsyopus** [comment]
Hello @gengkunling,  @arsalan993
I am experiencing the same issues. Did you manage to solve them?

**Comment by DreadPiratePsyopus** [comment]
Btw, @MichalBusta @arsalan993 @gengkunling @abhi-kumar 
Do I need to install the base caffe version first? And then recompile this custom version ?
Is it enough to use the custom version?

I managed to compile it after experiecing some issues, however I cannot import caffe from python. The error is:
Traceback (most recent call last):
  File "demo.py", line 10, in <module>
    import caffe
  File "/media/amafla/ssd/DeepTextSpotter/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
  File "/media/amafla/ssd/DeepTextSpotter/caffe/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: No module named _caffe

I already added the caffe path to ~/.bashrc but it is not working....
export PYTHONPATH=/media/mount/ssd/DeepTextSpotter/caffe/python:$PYTHONPATH

I am missing something? please your help.

**Comment by MichalBusta** [comment]
Hi,

On 05/22/2018 01:27 PM, DreadPiratePsyopus wrote:
>
> Btw, @MichalBusta <https://github.com/MichalBusta> @arsalan993 
> <https://github.com/arsalan993> @gengkunling 
> <https://github.com/gengkunling> @abhi-kumar 
> <https://github.com/abhi-kumar>
> Do I need to install the base caffe version first? And then recompile 
> this custom version ?
> Is it enough to use the custom version?
>
just custom version.
>
> I managed to compile it after experiecing some issues, however I 
> cannot import caffe from python. The error is:
> Traceback (most recent call last):
> File "demo.py", line 10, in
> import caffe
> File "/media/amafla/ssd/DeepTextSpotter/caffe/python/caffe/*init*.py", 
> line 1, in
> from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, 
> RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
> File 
> "/media/amafla/ssd/DeepTextSpotter/caffe/python/caffe/pycaffe.py", 
> line 13, in
> from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver,
> ImportError: No module named _caffe
>
try to find _caffe.so and add it to your python path.
>
> I already added the caffe path to ~/.bashrc but it is not working....
> export 
> PYTHONPATH=/media/mount/ssd/DeepTextSpotter/caffe/python:$PYTHONPATH
>
so maybe if you did not run "make install" on caffe you will need also: 
PYTHONPATH=/media/mount/ssd/DeepTextSpotter/caffe/python:/media/mount/ssd/DeepTextSpotter/caffe/build/lib:$PYTHONPATH

if you can not find _caffe.so = you compiled caffe without python 
support (and check if you are using python2)

**Comment by DreadPiratePsyopus** [comment]
Hello @MichalBusta ,
Thanks for your reply. I managed to compile caffe and it seems your custom version is working properly. However, now I am getting the following error:

WARNING: Logging before InitGoogleLogging() is written to STDERR
W0522 15:33:14.484016 19181 _caffe.cpp:135] DEPRECATION WARNING - deprecated use of Python interface
W0522 15:33:14.484047 19181 _caffe.cpp:136] Use this instead (with the named "weights" parameter):
W0522 15:33:14.484053 19181 _caffe.cpp:138] Net('/media/amafla/ssd/DeepTextSpotter/models/tiny.prototxt', 1, weights='/media/amafla/ssd/DeepTextSpotter/models/tiny.caffemodel')
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 513:14: Message type "caffe.LayerParameter" has no field named "reorg_param".
F0522 15:33:14.485894 19181 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: /media/amafla/ssd/DeepTextSpotter/models/tiny.prototxt
*** Check failure stack trace: ***
Aborted (core dumped)

Any clue why can be this happening?

Thanks in advance.

**Comment by MichalBusta** [comment]
On 05/22/2018 03:36 PM, DreadPiratePsyopus wrote:
>
> Hello @MichalBusta <https://github.com/MichalBusta> ,
> Thanks for your reply. I managed to compile caffe and it seems your 
> custom version is working properly. However, now I am getting the 
> following error:
>
> WARNING: Logging before InitGoogleLogging() is written to STDERR
> W0522 15:33:14.484016 19181 _caffe.cpp:135] DEPRECATION WARNING - 
> deprecated use of Python interface
> W0522 15:33:14.484047 19181 _caffe.cpp:136] Use this instead (with the 
> named "weights" parameter):
> W0522 15:33:14.484053 19181 _caffe.cpp:138] 
> Net('/media/amafla/ssd/DeepTextSpotter/models/tiny.prototxt', 1, 
> weights='/media/amafla/ssd/DeepTextSpotter/models/tiny.caffemodel')
> [libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing 
> text-format caffe.NetParameter: 513:14: Message type 
> "caffe.LayerParameter" has no field named "reorg_param".
> F0522 15:33:14.485894 19181 upgrade_proto.cpp:88] Check failed: 
> ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter 
> file: /media/amafla/ssd/DeepTextSpotter/models/tiny.prototxt
> *** Check failure stack trace: ***
> Aborted (core dumped)
>
> Any clue why can be this happening?
>
A: your python see other version of caffe
B: you forgot to checkout correct branch:

|git checkout darknet|
