### ISSUE TITLE
cmp_trie undefined symbol error on running demo.py

### ISSUE THREAD

**Issue by frozenscrypt** [MichalBusta/DeepTextSpotter#29]
I want to run deeptextspotter in CPU. Is it possible to run deeptextspotter on CPU or not?. After installations on running demo.py , I face the issue :

> import cmp_trie
> ImportError: /home/vivek/DeepTextSpotter/cmp_trie.so: undefined symbol: _ZN2cv28rotatedRectangleIntersectionERKNS_11RotatedRectES2_RKNS_12_OutputArrayE

**Comment by MichalBusta** [comment]
On 04/06/2018 08:53 AM, Vivek Tiwari wrote:
>
> I want to run deeptextspotter in CPU. Is it possible to run 
> deeptextspotter on CPU or not?. After installations on running demo.py 
> , I face the issue :
>
yes
>
>     import cmp_trie
>     ImportError: /home/vivek/DeepTextSpotter/cmp_trie.so: undefined
>     symbol:
>     _ZN2cv28rotatedRectangleIntersectionERKNS_11RotatedRectES2_RKNS_12_OutputArrayE
>
- opencv version (mismatched compile/runtime version)? (you can build 
opencv static, link static and you have no dependency on system libs) - 
or just comment out import cmp_trie if you do not need dictionary decoding

**Comment by frozenscrypt** [comment]
Hi,

Thank you for your response. Which opencv version  will match the compile
time/run time version? Also Will deeptextspotter run without warp-ctc?

**Comment by MichalBusta** [comment]
On 04/06/2018 09:13 AM, Vivek Tiwari wrote:
> Hi,
>
> Thank you for your response. Which opencv version will match the compile
> time/run time version? 
3. something - master branch on github
> Also Will deeptextspotter run without warp-ctc?
yes, you need ctc just for training

**Comment by frozenscrypt** [comment]
There is another issue when running demo.py:
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0406 14:34:22.201244  4245 _caffe.cpp:139] DEPRECATION WARNING -
deprecated use of Python interface
W0406 14:34:22.201268  4245 _caffe.cpp:140] Use this instead (with the
named "weights" parameter):
W0406 14:34:22.201272  4245 _caffe.cpp:142]
Net('/home/npr/DeepTextSpotter/models/tiny.prototxt', 1,
weights='/home/npr/DeepTextSpotter/models/tiny.caffemodel')
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing
text-format caffe.NetParameter: 513:14: Message type "caffe.LayerParameter"
has no field named "reorg_param".
F0406 14:34:22.202250  4245 upgrade_proto.cpp:90] Check failed:
ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file:
/home/npr/DeepTextSpotter/models/tiny.prototxt
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by MichalBusta** [comment]
Readme

  - installation - step one

**Comment by zhuliqian** [comment]
I have the same question.
 File "demo.py", line 21, in <module>
    from utils import get_normalized_image, print_seq_ext, print_seq2, get_obox, process_splits
  File "/home/chase/DeepTextSpotter/caffe/DeepTextSpotter-master/utils.py", line 12, in <module>
    import cmp_trie
ImportError: /home/chase/DeepTextSpotter/caffe/DeepTextSpotter-master/build/cmp_trie.so: undefined symbol: _ZN2cv28rotatedRectangleIntersectionERKNS_11RotatedRectES2_RKNS_12_OutputArrayE
 how can i solve this question
thank you very much

**Comment by MDavidFMY** [comment]
I meet the same question:
Traceback (most recent call last):
  File "demo.py", line 21, in <module>
    from utils import get_normalized_image, print_seq_ext, print_seq2, get_obox, process_splits
  File "/home/mdw/caffe/DeepTextSpotter/utils.py", line 12, in <module>
    import cmp_trie
ImportError: No module named cmp_trie

what should i do,thanks

**Comment by Rubseena** [comment]
Hi,
   On running demo.py,I got the following error:


Traceback (most recent call last):
  File "demo.py", line 23, in <module>
    import cmp_trie
ImportError: No module named cmp_trie.

Please provide the Solution..

**Comment by MichalBusta** [comment]
Hi,

Readme -> Installation -> step 3
