### ISSUE TITLE
why there No module named caffe? but i have  make in caffe with [100%] Built target cmp_trie

### ISSUE THREAD

**Issue by zhLawliet** [MichalBusta/DeepTextSpotter#37]
$ make
[ 50%] Built target trie_py
[100%] Built target cmp_trie

when
python demo.py
Traceback (most recent call last):
  File "demo.py", line 10, in <module>
    import caffe
ImportError: No module named caffe

**Comment by MichalBusta** [comment]
Readme - Installation - step 1

**Comment by lo-pan** [comment]
I also make caffe successfully.but when i run python demo.py,i also have this problem
"Traceback (most recent call last):
File "demo.py", line 10, in 
import caffe
ImportError: No module named caffe"
 

my caffe is downloaded by Installation -step1,
Do you solve this problem?If you solve it,please help me.
thanks!
